links:
  -
    path: /
    priority: '1.0'
    changefreq: daily
  -
    path: '/ksiazka/{taxonomy}/{node_title}'
    priority: '0.5'
    changefreq: ''
  -
    path: '/autor/{name_and_surname}'
    priority: '0.5'
    changefreq: ''
  -
    path: '/wydawnictwo/{title}'
